### ISSUE TITLE
base64 et utf-8 dans le navigateur

### ISSUE THREAD

**Issue by DavidBruant** [Scribouilli/scribouilli#1]
Pfffou ! Psykokwak !!
Jme mets des notes pour moi-même

- Github API veut de la base64 pour son contenu. Et plus précisément, attend que si c'est du texte, ce texte doit être encodé en utf-8
- `btoa` encode par défaut l'encodage par défaut de JS (UTF-16), donc vu que github essaye de le lire comme utf-8, y'a conflit
- le but, c'est de produire une version du contenu de l'utilisateur qui est une représentation base64 d'une représentation utf-8 du contenu
    - [TextEncoder.encode(str)](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) produit un `Uint8Array` qui représente la chaine en utf-8, mais ça a pas l'air simple d'en tirer du base64
    - node.js a résolu le problème via [`Buffer`](https://nodejs.org/api/buffer.html) (`Buffer.from(str).toString('base64')` #élégance). Ça n'existe pas de manière standard dans le navigateur, mais y'a une [lib qui émule](https://www.npmjs.com/package/buffer) et apparemment, y'a une version sans bundler, don c'est ptèt une solution qui marche pour nous

**Comment by elegaanz** [comment]
Je crois qu'on peut fermer cette issue maintenant qu'on ne passe plus par l'API GitHub.
